spring:
  application:
    name: Al-Baraka-Digital

  datasource:
    url: jdbc:mysql://localhost:3307/albaraka
    username: username
    password: userpassword
    driver: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect