spring:
  application:
    name: Al-Baraka-Digital

  datasource:
    url: jdbc:mysql://localhost:3306/albaraka
    username: root
    password: lakroune
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/albaraka
          jwk-set-uri: http://keycloak:8080/realms/albaraka/protocol/openid-connect/certs

jwt:
  secret: Ys+5/eaN0bFKzDSqnnM66Zvbu3KGFaUOAmmwnj531ZeR88YTx9G1/bQM860XWaKr3+PYZdmfKdGzY6DtKC9Ieg==
  expiration: 86400000

cloudinary:
  cloud-name: dp8texxme
  api-key: 825271736176548
  api-secret: OddqWj3aAi493D-Tr_5L8ddotCw
